### ISSUE TITLE
Some questions about εmax

### ISSUE THREAD

**Issue by yizhezhang0418** [Open3DVLab/NeuRodin#1]
Hi, thanks for your excellent work!!!
I am confused about the ε<sub>max</sub> , which you have mentioned in chapter 4.3. 
How to define and calculate the ε<sub>max</sub> , I can not find a explanation in your paper.
Could you please explain this? Thanks.

**Comment by yyfz** [comment]
Hi! Thank you for your attention to our work. We have scaled the camera positions to a bounding box of [-1, 1] and set $\epsilon_{max}$ to 0.1 on data of all scales (https://github.com/Open3DVLab/NeuRodin/blob/main/nerfstudio/fields/neurodin_field.py#L268). 

We have not tuned this parameter because we believe it will not have a significant impact on the results—just ensuring it is not set too small (missing natural level set constraints of large-scale features) or too large (resulting in high variance in normal estimates for most regions).

**Comment by yizhezhang0418** [comment]
Thanks for your reply!
